# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-20 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50, unique=True)),
                ('num_of_books', models.IntegerField()),
                ('rack_number', models.IntegerField()),
                ('published_date', models.DateField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_bookdetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
